custom:
  - >
    As the saying goes: 'The world needs more of this: "Made in USA".'
    Though not built directly on U.S. soil, this project embodies the
    American spirit—championing freedom, democracy, human rights, and privacy.
    Your support means a great deal to keep this mission alive.
    Thank you! 
    BTC: bc1qkkjps03mr0f98qw36kvrfcs04hxjjmah8840zj
    LTC: ltc1q3ll65nzh35lnmj0gygmzvhpz7vt0dpgr4f6yth
